// 浙江省教师招聘数据（2026届公告，共91条：小学65条 + 初中/高中/幼儿园第二批16条 + 特殊教育专项10条）
// 数据来源：各地教育局/政府官网公告，检索整理 2026-08-31
// 特殊教育说明：特教岗无独立学段，本项目统一归入「小学」学段 tab（id 82-91）
// rules 字段说明：
//   stage: 学段（"小学" / "中学" / "幼儿园、小学" 等，含即显示）
//   hukou: "none"=不限 / "zhejiang"=浙江省 / 具体市或区县名 / "unknown"=待核实
//   needMaster: 是否必须硕士
//   schoolGate: 院校门槛（null=无 / 文字描述）
//   honorGate: 荣誉门槛（null=无 / 文字描述）
//   certLevel: "none"=应届可后补 / "any"=相应学科教资 / "primary"=小学及以上 / "junior"=初中及以上 / "senior"=高中及以上 / "unknown"=待核实
//   audience: "fresh"=应届/社会均可 / "in-service"=仅面向在职在编教师
//   subjects: 岗位招的学科（[] = 多学科统招/不限；单学科岗位用于专业+教资匹配，考哪门课就要哪门教资）
//   注：hukou 为 "unknown" 的，匹配引擎默认按"需浙江省户籍"处理
const JOBS = [
  // ============ 杭州市 ============
  { id: 1, city: "杭州市", district: "萧山区", batch: "提前批", early: true, stage: "小学、中学",
    title: "杭州市萧山区面向2026届高校毕业生提前批招聘教师公告",
    posts: "江南小学、亚运村实验小学、文渊实验小学、南城小学、城东小学、通惠小学、高桥小学、湘湖小学等",
    count: "245名（中小学），其中小学岗位73个（语文28、数学22等）",
    staffing: "事业编", enroll: "2026年1月15日-1月22日", exam: "笔试2月1日；面试2月9日",
    condition: "2026届本科及以上；浙江省户籍或生源（博士、教育部直属高校不限）；本科须成绩前30%或校级及以上荣誉/省师范生技能赛三等奖/校二等奖学金之一；2026年8月31日前取得教资证",
    url: "https://www.xiaoshan.gov.cn/col/col1228964830/art/2026/art_f42efb0b45c0421590dd5129020e8669.html",
    rules: { stage: "小学、中学", hukou: "zhejiang", needMaster: false, schoolGate: null, honorGate: "校级及以上荣誉或校二等奖学金", certLevel: "none", audience: "fresh" } },

  { id: 2, city: "杭州市", district: "余杭区", batch: "提前批", early: true, stage: "小学、中学",
    title: "余杭区第一批公开招聘教师公告",
    posts: "全区各小学统配",
    count: "300名，其中小学64人",
    staffing: "事业编", enroll: "2026年1月12日-1月16日", exam: "笔试详见公告",
    condition: "硕士须获国奖/省奖/省师范生技能赛三等奖或校级综合荣誉（余杭户籍可放宽至院级）；本科师范须省级及以上荣誉",
    url: "https://sydw.huatu.com/2026/0108/2845793.html",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: "本科须省级及以上荣誉", certLevel: "any", audience: "fresh" } },

  { id: 3, city: "杭州市", district: "富阳区", batch: "校园招聘", early: true, stage: "小学、中学",
    title: "富阳区面向2026届毕业生校园招聘公告",
    posts: "全区各中小学",
    count: "143名，其中小学27人",
    staffing: "事业编", enroll: "2026年1月16日-1月22日", exam: "学校考核（试讲+结构化/技能测试）",
    condition: "2026届毕业生；38周岁以下（博士43）；小学岗可按学历专业或教资证学科报考",
    url: "https://hz.bendibao.com/job/2026114/168472.shtm",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 4, city: "杭州市", district: "临安区", batch: "提前批", early: true, stage: "小学、中学",
    title: "临安区面向优秀应届毕业生提前批招聘公告",
    posts: "岗位含中小学",
    count: "48名，小学分项人数未查到",
    staffing: "事业编", enroll: "2026年1月28日-2月3日", exam: "笔试2月7日",
    condition: "面向优秀应届毕业生（详见公告）",
    url: "https://www.shanxiangjiaoyu.com/zixun/20250909/66310.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: "unknown", certLevel: "unknown", audience: "fresh" } },

  // ============ 绍兴市 ============
  { id: 5, city: "绍兴市", district: "越城区", batch: "提前批", early: true, stage: "小学",
    title: "越城区新教师招聘公告（一）",
    posts: "全区各小学统配",
    count: "92名，小学岗：语文4、数学2、英语2、科学1、美术1、信息技术1",
    staffing: "事业编", enroll: "2025年12月1日-12月9日", exam: "两轮面试（结构化+试讲答辩）",
    condition: "户籍不限；2026届硕士，或一段线/提前批录取的本科师范生且获省优毕、校综二等奖学金、省师范生技能赛三等奖或专业排名前20%；30周岁以下",
    url: "https://www.sxyc.gov.cn/col/col1229445083/art/2025/art_83c23e5d7c0e452487e326eaf6bf763b.html",
    rules: { subjects: ["语文", "数学", "英语", "科学", "美术", "信息技术"], stage: "小学", hukou: "none", needMaster: false, schoolGate: null, honorGate: "校级综合奖学金（本科通道）", certLevel: "none", audience: "fresh" } },

  { id: 6, city: "绍兴市", district: "柯桥区", batch: "社招统考", early: false, stage: "小学",
    title: "柯桥区教体系统新教师公开招聘（三）",
    posts: "全区统一分配",
    count: "70名，其中小学9人（小学全科岗限退役军人）",
    staffing: "事业编", enroll: "2026年4月20日-4月28日", exam: "笔试5月16日",
    condition: "硕士或2026届师范本科或持证本科；小学全科限柯桥户籍/柯桥入伍退役军人",
    url: "https://fenbi.com/page/exam-information-detail/465762739046400",
    rules: { stage: "小学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 7, city: "绍兴市", district: "柯桥区", batch: "储备教师", early: false, stage: "小学、中学",
    title: "柯桥区中小学储备教师招聘公告",
    posts: "全区中小学（派遣至各校）",
    count: "150名，其中小学119人（语文42、数学40、英语13、科学11等）",
    staffing: "劳动合同制（派遣，非编）", enroll: "2026年4月20日-4月28日", exam: "笔试5月16日",
    condition: "详见公告",
    url: "https://jiaoshi.huatu.com/2026/0417/2859562.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 8, city: "绍兴市", district: "诸暨市", batch: "社招统考", early: false, stage: "中学",
    title: "诸暨市事业编制教师公开招聘公告",
    posts: "以中学为主，小学岗位未明确",
    count: "58名",
    staffing: "事业编", enroll: "2026年4月20日-4月29日", exam: "笔试5月16日；面试6月13日",
    condition: "A类限未参加过诸暨往届教招的2026应届生（本科以上，持教资证或师范类毕业）",
    url: "https://www.zgsydw.com/zhejiang/20260420/1533747_1.html",
    rules: { stage: "中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  // ============ 湖州市 ============
  { id: 9, city: "湖州市", district: "吴兴区", batch: "赴高校提前批", early: true, stage: "小学、中学",
    title: "吴兴区公开招聘优秀教育人才公告",
    posts: "35个职位，以中学为主，小学岗见岗位表",
    count: "120名",
    staffing: "详见公告", enroll: "2025年12月23日-12月30日", exam: "现场资格复审+考核（浙师大、华东师大等）",
    condition: "面向2024-2026届：师范类硕士、双一流本科、部省属师范院校师范本科（均不限户籍），或浙江户籍师范本科+获奖；本科30周岁以下、硕士35以下",
    url: "https://m.sydw.huatu.com/2025/1224/2844603.html",
    rules: { stage: "小学、中学", hukou: "zhejiang", needMaster: false, schoolGate: null, honorGate: "获奖经历（浙江户籍师范本科通道）", certLevel: "none", audience: "fresh" } },

  { id: 10, city: "湖州市", district: "长兴县", batch: "社招", early: false, stage: "小学、中学",
    title: "长兴县教育局公开招聘教师公告",
    posts: "小学岗见岗位表",
    count: "49名（事业编29+报备员额20）",
    staffing: "事业编+报备员额", enroll: "2026年6月16日-6月25日", exam: "笔试6月27日",
    condition: "硕士及以上不限户籍；应届本科限浙江户籍、历届本科限长兴生源/户籍；未取证须2027年7月31日前取得",
    url: "https://jiaoshi.huatu.com/2026/0616/2865680.html",
    rules: { stage: "小学、中学", hukou: "zhejiang", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 11, city: "湖州市", district: "安吉县", batch: "社招", early: false, stage: "小学、中学",
    title: "安吉县教育系统公开招聘教师公告",
    posts: "中小学岗位，小学见岗位表",
    count: "教师20人+财务2人",
    staffing: "事业编", enroll: "公告发布之日起-4月27日", exam: "笔试5月16日",
    condition: "中小学岗为2026届本科及以上（专业对口或持教资），非2026届须持证；18-38周岁",
    url: "https://m.huatu.com/2026/0416/2859345.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 12, city: "湖州市", district: "德清县", batch: "提前批", early: true, stage: "小学",
    title: "德清县赴浙江师范大学择优招聘公告",
    posts: "小学岗见岗位表",
    count: "32名",
    staffing: "详见公告", enroll: "2025年10月25日-10月31日", exam: "笔试11月1日",
    condition: "详见公告",
    url: "https://www.zhaojiao.net/zhaojiao/show-165638.html",
    rules: { stage: "小学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: "unknown", certLevel: "unknown", audience: "fresh" } },

  // ============ 宁波市 ============
  { id: 13, city: "宁波市", district: "鄞州区", batch: "社招统考", early: false, stage: "小学、中学、幼儿园",
    title: "2026年鄞州区教育系统公开招聘教师公告",
    posts: "全区各校（笔试按小学段单独划线）",
    count: "中小学75名+幼儿园4名",
    staffing: "事业编", enroll: "2026年3月16日-3月20日", exam: "笔试另行通知",
    condition: "面向2024-2026应届毕业生及部分在岗教师；应届生须1年内取得教资证",
    url: "https://www.nbyz.gov.cn/col/col1229117192/art/2026/art_ed1448a24a6047dc8055ca9022749829.html",
    rules: { stage: "小学、中学、幼儿园", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 14, city: "宁波市", district: "海曙区", batch: "专项招聘", early: false, stage: "小学、中学",
    title: "海曙区公开招聘2026学年\"专曙优师\"教育人才（第二批）",
    posts: "义务段岗位（含小学）",
    count: "共52名",
    staffing: "事业编", enroll: "2026年4月17日-4月29日", exam: "未查到",
    condition: "应届生/社会人员/退役军人三类，户籍不限；年龄、证书等截止2026年4月17日",
    url: "https://www.haishu.gov.cn/col/col1229830338/art/2026/art_b573e43295b3ec269afe6af10b0ff729.html",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 15, city: "宁波市", district: "前湾新区", batch: "社招", early: false, stage: "小学",
    title: "前湾新区2026年事业编制教师招聘（第四批）",
    posts: "设小学岗位",
    count: "24名",
    staffing: "事业编", enroll: "未查到", exam: "未查到",
    condition: "2026届硕士及以上为主（部分放宽本科）；小学岗须持对应学段教资证",
    url: "http://www.qianwan.gov.cn/art/2026/4/27/art_1229023676_59032821.html",
    rules: { stage: "小学", hukou: "none", needMaster: true, schoolGate: null, honorGate: null, certLevel: "primary", audience: "fresh" } },

  { id: 16, city: "宁波市", district: "江北区", batch: "编外招聘", early: false, stage: "小学",
    title: "江北区公立学校编外教师招聘公告",
    posts: "派遣至江北区各公办小学",
    count: "小学语文15、数学8、英语5",
    staffing: "派遣制（非编）", enroll: "即日起至2026年8月30日", exam: "免笔试（直接面试）",
    condition: "详见公告",
    url: "https://ycyg.nbhr.org.cn/Article/Info?ClassGuid=45c2f5bb-5221-45a5-a7cc-da6eb580e79d",
    rules: { subjects: ["语文", "数学", "英语"], stage: "小学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  // ============ 舟山市 ============
  { id: 17, city: "舟山市", district: "市本级（定海/普陀/岱山/嵊泗）", batch: "选聘（在编调动）", early: false, stage: "小学",
    title: "舟山市教育局面向县（区）选聘教师公告",
    posts: "定海：语文4、数学3等；普陀：语文3、数学5等；岱山、嵊泗均有小学岗",
    count: "49名（均为小学岗位）",
    staffing: "事业编（县区间调动）", enroll: "2026年8月10日截止", exam: "8月13日试讲",
    condition: "面向各县区事业编在岗教师；须教资证+本科及以上+近五年考核合格；45周岁以下",
    url: "https://zj.zgjsks.com/html/2026/ksgg_0804/70993.html",
    rules: { stage: "小学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "in-service" } },

  { id: 18, city: "舟山市", district: "市本级", batch: "社招统考", early: false, stage: "中学",
    title: "舟山市上半年高中、初中教师招聘（第二批）",
    posts: "无小学岗位（仅高中、初中），供参考",
    count: "不适用",
    staffing: "事业编", enroll: "2026年6月17日截止", exam: "6月27日",
    condition: "2026年舟山社招统招仅限高中初中，小学岗位主要靠县区选聘等渠道",
    url: "https://m.toutiao.com/article/7647377266037309952",
    rules: { stage: "中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  // ============ 温州市 ============
  { id: 19, city: "温州市", district: "鹿城区", batch: "社招统考", early: false, stage: "小学、中学",
    title: "鹿城区2026年公开招聘教师公告",
    posts: "见岗位表（含小学体育S12等）",
    count: "44名",
    staffing: "事业编", enroll: "2026年6月8日-6月16日", exam: "笔试6月27日",
    condition: "鹿城区户籍为主（博士/应届硕士/双一流应届本科等可放宽至温州户籍）；本科以上+专业对口；持证或7月31日前取得教资证",
    url: "https://www.lucheng.gov.cn/col/col1229609437/art/2026/art_1f2ddfadfb5b46a183cca07dfa38eb7f.html",
    rules: { stage: "小学、中学", hukou: "鹿城区", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 20, city: "温州市", district: "龙湾区", batch: "社招统考", early: false, stage: "小学、中学",
    title: "龙湾区2026年公开招聘中小学教师公告",
    posts: "全区各中小学",
    count: "81名，其中小学41名",
    staffing: "事业编", enroll: "2026年6月16日-6月18日", exam: "笔试6月27日",
    condition: "户籍须符合岗位要求（应届生可凭生源地）；38周岁以下；专业以教资证及学历专业为准",
    url: "https://www.longwan.gov.cn/col/col1229664390/art/2026/art_ad8b3b16bf9d48838606e69af3108904.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 21, city: "温州市", district: "瓯海区", batch: "社招统考", early: false, stage: "小学、中学",
    title: "瓯海区教育系统2026年公开招聘公办中小学教师公告",
    posts: "全区各公办中小学",
    count: "21名，其中小学11名",
    staffing: "事业编", enroll: "详见公告", exam: "未查到",
    condition: "专业对口原则，以教资证及学历证书标注专业为准",
    url: "https://zw.admin.offcn.com/ggcx/gg/219880.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 22, city: "温州市", district: "泰顺县", batch: "社招统考", early: false, stage: "小学、中学",
    title: "泰顺县2026年公开招聘教师公告（第1号）",
    posts: "小学教育专业可报小学段学科",
    count: "43名",
    staffing: "事业编", enroll: "2026年6月22日-6月26日（现场报名）", exam: "另行通知",
    condition: "泰顺常住户口或籍贯（高学历/特教岗放宽）；本科及以上；高学段教资可报低学段",
    url: "https://www.ts.gov.cn/col/col1229246207/art/2026/art_551ae8f0a3e446959db003f1df183ba9.html",
    rules: { stage: "小学、中学", hukou: "泰顺县", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 23, city: "温州市", district: "平阳县", batch: "社招统考", early: false, stage: "小学、中学",
    title: "平阳县2026年中小学教师公开招聘公告",
    posts: "全县各中小学（含特校定向5名）",
    count: "92名",
    staffing: "事业编", enroll: "2026年6月12日-6月19日", exam: "后续笔试",
    condition: "详见公告附件",
    url: "https://www.zjpy.gov.cn/col/col1229252498/art/2026/art_69f734d55a444d1689ab2929eaa4da02.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  // ============ 嘉兴市 ============
  { id: 24, city: "嘉兴市", district: "平湖市", batch: "社招", early: false, stage: "小学",
    title: "平湖市教育局2026学年公开招聘教师公告",
    posts: "义务教育段统配岗位（含小学全科），另含特殊教育",
    count: "42名",
    staffing: "事业编", enroll: "2026年4月15日-4月22日", exam: "笔试5月10日；面试5月16-17日",
    condition: "本科及以上；18-38周岁；一般要求平湖户籍（硕士、一流大学、部属师范、浙师大、杭师大等不限）；应届可先无教资证，持小学教资报统配岗",
    url: "https://www.gaoxiaojob.com/announcement/detail/394150.html",
    rules: { stage: "小学", hukou: "平湖市", needMaster: false, schoolGate: "浙师大/杭师大等不限户籍", honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 25, city: "嘉兴市", district: "平湖市", batch: "校园招聘", early: true, stage: "小学、中学",
    title: "平湖市校园招聘2026学年教师（第三批）",
    posts: "见附件岗位表",
    count: "未明确（第三批）",
    staffing: "在编", enroll: "2026年3月12日-3月18日", exam: "未查到",
    condition: "2026年本科及以上应届（含国境外2025.8-2026.8毕业）；18-38周岁",
    url: "https://career.scnu.edu.cn/detail/online?id=3476413",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 26, city: "嘉兴市", district: "南湖区", batch: "提前批", early: true, stage: "小学、中学",
    title: "南湖区部分学校公开招聘优秀应届毕业生公告",
    posts: "全区部分学校",
    count: "61名，其中小学6名",
    staffing: "事业编", enroll: "网报至2025年11月11日", exam: "笔试11月15日；面试11月23日",
    condition: "2026届硕士（本科须师范）或师范类本科；38周岁以下；户籍不限；须有普通话证",
    url: "https://www.nanhu.gov.cn/art/2025/11/4/art_1229282434_5671414.html",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 27, city: "嘉兴市", district: "南湖区", batch: "校园招聘", early: true, stage: "小学",
    title: "南湖实验学校公开招聘公告",
    posts: "南湖实验学校（集团校）",
    count: "小学语文4、小学美术1",
    staffing: "事业编", enroll: "未查到", exam: "未查到",
    condition: "面向2026届优秀应届生，本科/学士起",
    url: "https://www.nanhu.gov.cn/art/2025/10/31/art_1229282434_5670272.html",
    rules: { subjects: ["语文", "美术"], stage: "小学", hukou: "none", needMaster: false, schoolGate: null, honorGate: "unknown", certLevel: "unknown", audience: "fresh" } },

  { id: 28, city: "嘉兴市", district: "秀洲区", batch: "高层次引进", early: true, stage: "小学、中学",
    title: "\"秀水泱泱\"教育高层次人才招聘（第一批）",
    posts: "全区各学校",
    count: "55名，其中小学23名",
    staffing: "事业编", enroll: "未查到", exam: "未查到",
    condition: "2026届硕士或师范类本科；38周岁以下（研究生43以下）；户籍不限",
    url: "https://www.xiuzhou.gov.cn/col/col1229406930/art/2025/art_8bfc0289242e41de88fe8ffce3b4625a.html",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 29, city: "嘉兴市", district: "秀洲区", batch: "社招", early: false, stage: "小学、中学、幼儿园",
    title: "秀洲区公开招聘中小学和幼儿园教师公告",
    posts: "全区各学校",
    count: "28名，其中小学7名",
    staffing: "事业编", enroll: "网报至2026年5月18日", exam: "笔试5月30日；面试6月7日",
    condition: "师范类本科或硕士或浙江省户籍2026届非师范本科；38岁以下；需相应教资（应届7月31日前取得）",
    url: "https://www.xiuzhou.gov.cn/col/col1229406930/art/2026/art_19bb4c30e1334a93902d92084245ad38.html",
    rules: { stage: "小学、中学、幼儿园", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 30, city: "嘉兴市", district: "经开区", batch: "提前批", early: true, stage: "小学、中学",
    title: "经开区面向2026届应届优秀毕业生招聘公告",
    posts: "全区各学校",
    count: "75名，其中小学14名",
    staffing: "事业编", enroll: "未查到", exam: "未查到",
    condition: "2026届师范本科或硕士；38岁以下（研究生43）；户籍不限",
    url: "https://job.sdgxbys.cn/campus/view/id/742811",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 31, city: "嘉兴市", district: "经开区", batch: "社招", early: false, stage: "小学、中学",
    title: "经开区2026年公开招聘公办中小学教师公告",
    posts: "全区各公办中小学",
    count: "20名",
    staffing: "事业编", enroll: "报名至2026年4月29日", exam: "未查到",
    condition: "本科及以上；38岁以下（副高放宽43）；需教资（应届8月31日前取得）",
    url: "https://rlsbj.jiaxing.gov.cn/col/col1229289160/art/2026/art_98d992042b8f4fec822056ce3172037a.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 32, city: "嘉兴市", district: "嘉善县", batch: "社招", early: false, stage: "小学、中学",
    title: "嘉善县2026年公开招聘教师公告",
    posts: "全县各学校",
    count: "37名，其中小学10名",
    staffing: "事业编+报备员额", enroll: "网报至2026年7月9日", exam: "笔试7月18日；面试7月19-20日",
    condition: "本科/学士；小学岗位需嘉善户籍或生源（硕士及一流高校等不限）；应届师范可后补教资至8月15日",
    url: "https://www.jiashan.gov.cn/col/col1229373860/art/2026/art_54e62addb911420d9d9e01a8f874d16d.html",
    rules: { stage: "小学、中学", hukou: "嘉善县", needMaster: false, schoolGate: "硕士及一流高校不限户籍", honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 33, city: "嘉兴市", district: "嘉善县", batch: "赴高校招聘", early: true, stage: "小学、中学、幼儿园",
    title: "嘉善县赴高校招聘优秀教师（第三批）",
    posts: "见岗位表",
    count: "57+2名，其中小学4名",
    staffing: "事业编", enroll: "未查到", exam: "未查到",
    condition: "2026届硕士/师范本科为主；38岁以下",
    url: "https://zw.admin.offcn.com/ggcx/gg/189309.html",
    rules: { stage: "小学、中学、幼儿园", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 34, city: "嘉兴市", district: "海盐县", batch: "提前批", early: true, stage: "小学、中学",
    title: "海盐县2026年第一批教师招聘公告",
    posts: "见岗位表",
    count: "62名",
    staffing: "事业编", enroll: "2025年10月启动", exam: "未查到",
    condition: "面向2025/2026届硕士及\"双一流\"/浙师大师范本科等；38岁以下；户籍不限",
    url: "https://www.haiyan.gov.cn/col/col1512827/art/2025/art_f389ec468c07f86b104b2e45fdf14fe4.html",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: "硕士或双一流/浙师大师范本科", honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 35, city: "嘉兴市", district: "海盐县", batch: "社招统考", early: false, stage: "小学、中学",
    title: "海盐县2026年教师招聘（第二批/统考）",
    posts: "见岗位表",
    count: "见岗位表",
    staffing: "事业编", enroll: "网报2026年5月6日-5月12日", exam: "未查到",
    condition: "详见官方公告",
    url: "https://www.haiyan.gov.cn/col/col1512827/art/2026/art_0f169cf9f35b321620adac034d9e0278.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 36, city: "嘉兴市", district: "海宁市", batch: "专项招聘", early: true, stage: "小学、中学",
    title: "海宁市教育系统2026年1月公开招聘公告",
    posts: "见岗位表",
    count: "87名+报备员额3名",
    staffing: "事业编+报备员额", enroll: "预报名至2026年1月9日", exam: "笔试1月11日；面试1月17日",
    condition: "2026届硕士或\"双一流\"/部属师范等优秀本科；18-38周岁；师范类需浙江户籍/生源",
    url: "https://zj.huatu.com/2025/1231/1963438.html",
    rules: { stage: "小学、中学", hukou: "zhejiang", needMaster: false, schoolGate: "双一流/部属师范等优秀本科", honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 37, city: "嘉兴市", district: "海宁市", batch: "社招", early: false, stage: "小学、中学",
    title: "海宁市教育系统2026年4月公开招聘公告",
    posts: "见岗位表",
    count: "57名+报备员额3名",
    staffing: "事业编+报备员额", enroll: "预报名至2026年4月24日", exam: "笔试5月10日；面试5月16-17日",
    condition: "本科及以上；18-38周岁；嘉兴市生源或户籍；须有相应教资",
    url: "https://baokao.offcn.com/ggcx/gg/200893/11.html",
    rules: { stage: "小学、中学", hukou: "嘉兴市", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 38, city: "嘉兴市", district: "桐乡市", batch: "社招", early: false, stage: "小学",
    title: "桐乡市教育系统公开招聘2026学年教师（第三批）",
    posts: "面向桐乡市各小学统配",
    count: "34名，其中小学语文2名",
    staffing: "事业编", enroll: "未查到", exam: "未查到",
    condition: "2026届为主；本科/学士；本科学历一般需嘉兴/桐乡户籍（研究生、桐乡生源不限）",
    url: "https://jiaoshi.huatu.com/2026/0609/2865027.html",
    rules: { subjects: ["语文"], stage: "小学", hukou: "嘉兴市", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 39, city: "嘉兴市", district: "桐乡市", batch: "提前批", early: true, stage: "小学、中学",
    title: "桐乡市面向优秀毕业生公开招聘（第二批）",
    posts: "见岗位表",
    count: "54名",
    staffing: "事业编", enroll: "未查到（赴浙大招聘）", exam: "未查到",
    condition: "2026届毕业生，户籍不限，需获奖学金等条件之一",
    url: "https://zj.huatu.com/2026/0520/1966419.html",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: "奖学金等条件之一", certLevel: "unknown", audience: "fresh" } },

  { id: 40, city: "嘉兴市", district: "港区", batch: "校园招聘", early: true, stage: "小学、中学",
    title: "嘉兴港区（乍浦经开区）教育系统招聘高校毕业生公告",
    posts: "见岗位表",
    count: "见岗位表",
    staffing: "事业编", enroll: "未查到", exam: "未查到",
    condition: "应届为主，须7月31日前取得教资；港区服务期5年",
    url: "https://www.rsks.cn/zhejiang/jiaxing/243370.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  // ============ 金华市 ============
  { id: 41, city: "金华市", district: "婺城区", batch: "提前批", early: true, stage: "小学、中学",
    title: "婺城区面向2026届优秀毕业生招聘公告",
    posts: "见岗位表",
    count: "22名",
    staffing: "事业编", enroll: "2025年10月29日-11月9日", exam: "未查到",
    condition: "2026届毕业生，专业对口，38岁以下",
    url: "http://www.wuch.gov.cn/art/2025/10/23/art_1229713696_4305763.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: "unknown", certLevel: "unknown", audience: "fresh" } },

  { id: 42, city: "金华市", district: "婺城区", batch: "社招", early: false, stage: "小学、中学",
    title: "婺城区2026年教育局下属学校招聘公告",
    posts: "见附件（含中小学）",
    count: "事业编32名+合同制27名",
    staffing: "事业编/合同制", enroll: "2026年5月22日-5月28日", exam: "笔试6月7日",
    condition: "浙江省内户籍或生源；本科及以上；需相应教资",
    url: "https://www.wuch.gov.cn/col/col1229713696/art/2026/art_fbf5d6872eba4d149997864e2e1f5aee.html",
    rules: { stage: "小学、中学", hukou: "zhejiang", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 43, city: "金华市", district: "义乌市", batch: "社招", early: false, stage: "小学、中学",
    title: "义乌市2026年教育系统公开招聘公告",
    posts: "小学语文分片区定向全市各小学、部分城区及镇街学校",
    count: "中小学524名（事业编203+备案制321），另幼儿园40名",
    staffing: "事业编+备案制", enroll: "2026年3月13日-3月23日", exam: "未查到",
    condition: "本科及以上；1988年3月13日后出生；户籍不限；2026届免教资要求",
    url: "https://www.yw.gov.cn/col/col1229129404/art/2026/art_90d721f8eb19486bb0ced310e746fdee.html",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 44, city: "金华市", district: "东阳市", batch: "社招", early: false, stage: "小学、中学",
    title: "东阳市教育系统公开招聘事业编教师公告",
    posts: "见岗位表",
    count: "39名（小学岗须本科及以上，专业不限）",
    staffing: "事业编", enroll: "报名至2026年3月20日", exam: "未查到",
    condition: "浙江省户籍；1987年后出生；应届/双一流等免教资",
    url: "https://www.zgjsks.com/html/2026/zj_0313/816674.html",
    rules: { stage: "小学、中学", hukou: "zhejiang", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 45, city: "金华市", district: "永康市", batch: "社招", early: false, stage: "小学、中学",
    title: "永康市教育系统公开招聘事业编教师公告",
    posts: "见岗位表",
    count: "187名",
    staffing: "事业编", enroll: "2026年3月23日-3月27日", exam: "未查到",
    condition: "详见公告",
    url: "https://zj.offcn.com/html/jiaoshi/zhaokaoxinxi/zpgg/jinhua/",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 46, city: "金华市", district: "武义县", batch: "社招", early: false, stage: "小学、中学",
    title: "武义县教育系统公开招聘事业编教师公告",
    posts: "见岗位表",
    count: "42名",
    staffing: "事业编", enroll: "报名至2026年3月25日", exam: "未查到",
    condition: "详见公告",
    url: "https://zj.offcn.com/html/jiaoshi/zhaokaoxinxi/zpgg/jinhua/",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 47, city: "金华市", district: "浦江县", batch: "社招", early: false, stage: "小学、中学",
    title: "浦江县教育系统公开招聘教师公告",
    posts: "见岗位表（含小学岗）",
    count: "20名",
    staffing: "事业编", enroll: "2026年3月23日-3月27日", exam: "未查到",
    condition: "详见公告（本地户籍通常符合）",
    url: "https://zj.offcn.com/html/jiaoshi/zhaokaoxinxi/zpgg/jinhua/",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 48, city: "金华市", district: "磐安县", batch: "社招", early: false, stage: "小学、中学",
    title: "磐安县公开招聘教师及面向全国选聘公告",
    posts: "见岗位表",
    count: "招聘11名+面向全国选聘11名",
    staffing: "事业编", enroll: "2026年3月30日-4月8日", exam: "未查到",
    condition: "详见公告",
    url: "https://m.zhaojiao.net/zhaojiao/show-176330.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 49, city: "金华市", district: "金东区", batch: "社招", early: false, stage: "小学、中学",
    title: "金东区公开招聘教师公告（分三批）",
    posts: "见岗位表",
    count: "一批30名、二批15名、三批42名",
    staffing: "事业编", enroll: "3月25-31日 / 4月20-24日 / 7月6-10日", exam: "未查到",
    condition: "详见公告",
    url: "https://m.zhaojiao.net/zhaojiao/show-176330.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  // ============ 台州市 ============
  { id: 50, city: "台州市", district: "椒江区", batch: "社招统考", early: false, stage: "小学、中学、幼儿园",
    title: "椒江区2026年招聘中小学、幼儿园教师公告（一）",
    posts: "全区各校（择岗制）",
    count: "66名",
    staffing: "全额拨款事业编", enroll: "2026年5月8日-5月13日", exam: "笔试5月30日",
    condition: "教资可在聘用前取得；最低服务5年；每人限报一职",
    url: "http://career.zjnu.edu.cn/news/view/aid/431401/tag/jszp",
    rules: { stage: "小学、中学、幼儿园", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 51, city: "台州市", district: "路桥区", batch: "社招统考", early: false, stage: "小学、中学",
    title: "路桥区教育局公开招聘事业编制教师公告",
    posts: "全区各中小学",
    count: "32名",
    staffing: "全额拨款事业编", enroll: "2026年5月11日-5月15日（现场）", exam: "笔试5月30日",
    condition: "详见公告",
    url: "https://linhairc.com/zxxq_1472B343F60EB3A4.shtml",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 52, city: "台州市", district: "临海市", batch: "社招统考", early: false, stage: "小学、中学",
    title: "临海市中小学公开招聘新教师公告",
    posts: "见岗位表",
    count: "53名，其中小学语文1、小学科学1",
    staffing: "财政全额补助事业编", enroll: "2026年5月11日-5月15日（钉钉报名）", exam: "笔试5月30日",
    condition: "38周岁以下（博士放宽40）；户籍不限；教资可凭考试合格证明报考、7月31日前取证",
    url: "https://zw.admin.offcn.com/ggcx/gg/211668.html",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 53, city: "台州市", district: "温岭市", batch: "社招统考", early: false, stage: "小学、中学",
    title: "温岭市教育事业单位公开招聘教师公告",
    posts: "以初高中为主，含\"先在小学任教3年\"轮岗岗位",
    count: "53名",
    staffing: "事业编", enroll: "2026年5月8日-5月15日", exam: "笔试5月30日",
    condition: "详见公告",
    url: "https://zw.admin.offcn.com/zwcx/list/208840.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 54, city: "台州市", district: "玉环市", batch: "社招统考", early: false, stage: "小学、中学",
    title: "玉环市公开招聘事业编制教师公告（第二批）",
    posts: "全区各学校",
    count: "98名，其中小学语文5、小学信息技术3（另有数学/英语/科学等若干）",
    staffing: "全额拨款事业编", enroll: "2026年5月11日-5月15日", exam: "笔试5月30日",
    condition: "本科及以上+学位；38周岁以下；户籍不限；按所学专业或教资证学科报考；语文岗普通话二甲",
    url: "https://www.zgsydw.com/zhejiang/20260512/1558413_1.html",
    rules: { stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 55, city: "台州市", district: "天台县", batch: "社招统考", early: false, stage: "中学",
    title: "天台县教育局公开招聘教师公告",
    posts: "无小学岗位（高中语数外化+特教2+学前1），供参考",
    count: "14名（不含小学）",
    staffing: "全额事业编", enroll: "2026年5月11日-5月15日", exam: "笔试5月30日",
    condition: "详见公告",
    url: "https://www.zgsydw.com/zhejiang/20260511/1557127_1.html",
    rules: { stage: "中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  // ============ 衢州市 ============
  { id: 56, city: "衢州市", district: "柯城区", batch: "社招", early: false, stage: "小学、中学",
    title: "柯城区公开招聘教职工公告",
    posts: "统一分配区属学校（中小学语文/数学/科学、初中社会/英语、特教、幼儿、营养师）",
    count: "29名：中小学语文9、数学3、科学4，初中社会5、英语1，特教3，幼儿3，营养师1",
    staffing: "事业编", enroll: "2026年6月25日-7月1日", exam: "笔试初定7月11日",
    condition: "户籍不限；38周岁以下；应届本科须师范类专业，社会人员须本科及以上；须初中及以上教资（小学岗可报）；服务满5年",
    url: "https://www.kecheng.gov.cn/col/col1229769719/art/2026/art_4a312a9619a04289b8e4504cc6816d92.html",
    rules: { subjects: ["语文", "数学", "科学", "英语"], stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "junior", audience: "fresh" } },

  { id: 57, city: "衢州市", district: "衢江区", batch: "社招", early: false, stage: "中学",
    title: "衢江区教育系统公开招聘教师公告",
    posts: "正文仅高中/中职/初中/幼儿园岗",
    count: "10名",
    staffing: "事业编", enroll: "2026年5月22日-5月29日", exam: "笔试初定6月13日",
    condition: "户籍不限；38周岁以下；高中岗须硕士（连续任教者可放宽本科），初中/幼儿园岗本科及以上",
    url: "https://m.huatu.com/2026/0520/2862991.html",
    rules: { stage: "中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 58, city: "衢州市", district: "龙游县", batch: "社招", early: false, stage: "中学",
    title: "龙游县公开招聘新教师公告",
    posts: "以中学岗为主（全岗须高中教资证）",
    count: "16名",
    staffing: "事业编", enroll: "2026年6月23日-7月1日", exam: "笔试7月11日",
    condition: "户籍不限；38周岁以下；本科及以上；须高中学段教资",
    url: "https://www.longyou.gov.cn/col/col1339784/art/2026/art_dc10e4c4838a4847b79e777ff4269cb5.html",
    rules: { stage: "中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "senior", audience: "fresh" } },

  { id: 59, city: "衢州市", district: "开化县", batch: "选调（县内）", early: false, stage: "小学",
    title: "开化县城区部分学校选调教师公告",
    posts: "实验小学、北门小学、天地小学、城东小学等",
    count: "25名，其中小学岗13人",
    staffing: "在编选调", enroll: "2026年7月31日（现场）", exam: "选调无笔试",
    condition: "面向县内农村在编教师；本科及以上；40周岁以下；同学段岗须乡镇任教满3年",
    url: "https://www.zgjsks.com/html/2026/zj_0727/861501.html",
    rules: { stage: "小学", hukou: "开化县", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "in-service" } },

  // ============ 丽水市 ============
  { id: 60, city: "丽水市", district: "遂昌县", batch: "社招", early: false, stage: "小学",
    title: "遂昌县教育系统公开招聘教师公告",
    posts: "全部为小学岗位",
    count: "4名：小学音乐1、体育2、美术1",
    staffing: "小学事业编", enroll: "2026年5月8日-5月13日", exam: "笔试5月23日",
    condition: "限户籍（详见计划表）",
    url: "https://zj.zgjsks.com/html/2026/kszx_0225/70165.html",
    rules: { subjects: ["音乐", "体育", "美术"], stage: "小学", hukou: "遂昌县", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 61, city: "丽水市", district: "松阳县", batch: "社招", early: false, stage: "小学、中学、幼儿园",
    title: "松阳县公开招聘中小学幼儿园教师公告（一）",
    posts: "中小学体育岗（户籍不限）等",
    count: "10名",
    staffing: "事业编", enroll: "2026年5月12日-5月18日（钉钉）", exam: "笔试见准考证",
    condition: "18-38周岁；中小学体育岗户籍不限，学前岗限松阳户籍；本科及以上；须相应教资",
    url: "https://www.zgsydw.com/zhejiang/20260507/1554935_1.html",
    rules: { subjects: ["体育"], stage: "小学、中学、幼儿园", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 62, city: "丽水市", district: "龙泉市", batch: "社招", early: false, stage: "中学",
    title: "龙泉市公开招聘教师公告",
    posts: "以初中、高中岗位为主，供参考",
    count: "11名",
    staffing: "事业编", enroll: "2026年5月9日-5月15日", exam: "笔试5月23日",
    condition: "详见公告",
    url: "https://renshiksw.com/a/563488.html",
    rules: { stage: "中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 63, city: "丽水市", district: "缙云县", batch: "社招", early: false, stage: "小学、中学",
    title: "缙云县教育局下属学校公开招聘教师公告",
    posts: "见岗位表（附件1）",
    count: "7名",
    staffing: "事业编", enroll: "2026年6月2日-6月8日", exam: "笔试6月27日",
    condition: "限缙云户籍或生源（非在职硕士及以上不限）；本科及以上；18-38周岁；须相应教资",
    url: "https://www.zgsydw.com/zhejiang/20260529/1571950_1.html",
    rules: { stage: "小学、中学", hukou: "缙云县", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 64, city: "丽水市", district: "莲都区", batch: "社招", early: false, stage: "小学、中学",
    title: "莲都区教育局公开招聘教师公告",
    posts: "见岗位表（附件1）",
    count: "19名",
    staffing: "事业编", enroll: "2026年7月6日-7月8日", exam: "未查到",
    condition: "限丽水户籍或生源（研究生不限）；本科及以上+学位；38周岁以下；须相应学科教资",
    url: "https://m.huatu.com/2026/0629/2866689.html",
    rules: { stage: "小学、中学", hukou: "丽水市", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 65, city: "丽水市", district: "庆元县", batch: "提前批+统考", early: true, stage: "小学、中学、幼儿园",
    title: "庆元县2026年提前批及统考批教师招聘公告",
    posts: "见附件岗位表",
    count: "提前批5名；统考批6名",
    staffing: "全额事业编", enroll: "提前批至2025年11月11日；统考批2026年4月28日-5月7日", exam: "统考笔试5月16日",
    condition: "提前批面向2026届应届（含2024/2025届）；18-38周岁",
    url: "https://www.zjqy.gov.cn/col/col1229432649/art/2025/art_28e4092fa33544c8af51af703e483218.html",
    rules: { stage: "小学、中学、幼儿园", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: "unknown", certLevel: "unknown", audience: "fresh" } },

  // ============ 第二批：初中/高中/幼儿园（检索整理 2026-08-31） ============
  { id: 66, city: "台州市", district: "三门县", batch: "社招统考", early: false, stage: "中学",
    title: "2026年三门县中学教师公开招聘公告",
    posts: "初中/高中各学科（见计划表）",
    count: "6名",
    staffing: "事业编", enroll: "2026年5月11日-5月15日（现场报名，三门县教育局）", exam: "详见公告",
    condition: "户籍不限；限2026届应届毕业生；38周岁以下（博士40）；须相应教师资格证（应届可凭教资考试合格证明/面试凭证/师范生身份证明报考，2026年7月31日前提交证书）；普通话二级乙等",
    url: "http://qssy.zjks.com/tyzpwb/website/queryDetail.htm?mkxh=2&tzid=2708",
    rules: { stage: "中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 67, city: "嘉兴市", district: "嘉善县", batch: "社招统考", early: false, stage: "高中",
    title: "嘉善县教育局2026年公开招聘教师公告（高中岗）",
    posts: "高中教师（含综合高中）",
    count: "7名",
    staffing: "事业编", enroll: "详见公告（38周岁以下）", exam: "详见公告",
    condition: "高中岗户籍不限；各岗位学历/专业/教资要求见岗位表；另有技师学院报备员额5名",
    url: "https://www.jiashan.gov.cn/col/col1229373860/art/2026/art_54e62addb911420d9d9e01a8f874d16d.html",
    rules: { stage: "高中", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 68, city: "嘉兴市", district: "嘉善县", batch: "社招统考", early: false, stage: "初中",
    title: "嘉善县教育局2026年公开招聘教师公告（初中岗）",
    posts: "初中教师",
    count: "18名",
    staffing: "事业编", enroll: "详见公告（38周岁以下）", exam: "详见公告",
    condition: "初中岗限嘉兴市户籍或嘉兴籍生源（硕士/副高/双一流/部属师范及浙师大杭师大等本科不限户籍）；各岗位要求见岗位表",
    url: "https://www.jiashan.gov.cn/col/col1229373860/art/2026/art_54e62addb911420d9d9e01a8f874d16d.html",
    rules: { stage: "初中", hukou: "嘉兴市", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 69, city: "嘉兴市", district: "嘉善县", batch: "社招统考", early: false, stage: "幼儿园、小学",
    title: "嘉善县教育局2026年公开招聘教师公告（小学、幼儿园岗）",
    posts: "小学教师、学前教育教师",
    count: "小学10名、幼儿园2名",
    staffing: "事业编", enroll: "详见公告（38周岁以下）", exam: "详见公告",
    condition: "小学/幼儿园岗限嘉善县户籍或嘉善籍生源（硕士/副高/双一流/部属师范及浙师大杭师大等本科不限户籍）；各岗位要求见岗位表",
    url: "https://www.jiashan.gov.cn/col/col1229373860/art/2026/art_54e62addb911420d9d9e01a8f874d16d.html",
    rules: { stage: "幼儿园、小学", hukou: "嘉善县", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 70, city: "台州市", district: "临海市", batch: "提前批", early: true, stage: "初中",
    title: "临海市教育系统(初中)面向2026年普通高校毕业生公开招聘教师公告",
    posts: "全市初中各学科（见计划表）",
    count: "12名",
    staffing: "全额补助事业编", enroll: "网上/现场报名（详见公告）", exam: "详见公告",
    condition: "2026届本科及以上；30周岁以下（博士40）；户籍不限；专业对口；须满足之一：博士/硕士/省优毕/部属或双一流本科/浙师大初阳学院或杭师大经亨颐实验班/省师范生技能赛三等奖及以上/高考特控线+校级专业奖学金/高中学科奥赛获奖/国奖或省政府奖学金",
    url: "https://www.linhai.gov.cn/art/2025/12/26/art_1229517351_4086978.html",
    rules: { stage: "初中", hukou: "none", needMaster: false, schoolGate: null, honorGate: "校级专业奖学金（另须高考达特控线，多通道详见公告）", certLevel: "unknown", audience: "fresh" } },

  { id: 71, city: "台州市", district: "临海市", batch: "提前批", early: true, stage: "高中",
    title: "临海市教育系统(高中)面向2026年普通高校毕业生公开招聘教师公告",
    posts: "全市高中各学科（见计划表）",
    count: "25名",
    staffing: "全额补助事业编", enroll: "网上/现场报名（详见公告）", exam: "详见公告",
    condition: "2026届本科及以上；30周岁以下（博士40）；户籍不限；专业对口；须满足之一：博士/硕士/省优毕/部属或双一流本科/浙师大初阳学院或杭师大经亨颐实验班/省师范生技能赛三等奖及以上/高考特控线+校级专业奖学金/高中学科奥赛获奖/国奖或省政府奖学金",
    url: "https://www.linhai.gov.cn/art/2025/10/24/art_1229517351_4078826.html",
    rules: { stage: "高中", hukou: "none", needMaster: false, schoolGate: null, honorGate: "校级专业奖学金（另须高考达特控线，多通道详见公告）", certLevel: "unknown", audience: "fresh" } },

  { id: 72, city: "衢州市", district: "衢江区", batch: "校园招聘（浙师大专场）", early: true, stage: "中学",
    title: "衢江区赴浙江师范大学面向2026年优秀应届毕业生招聘教师公告",
    posts: "高中英语1、高中历史1、中职数学1、中职电气自动化1、初中英语1、初中心理健康1",
    count: "6名",
    staffing: "事业编", enroll: "网上预报名至2026年3月18日12:00", exam: "详见公告",
    condition: "2026届硕士及以上（基层服务期满未入编者视同应届）；户籍不限；研究生教育学类或本科师范类专业；38周岁以下（博士43）；教资2026年8月31日前取得或凭考试合格证明",
    url: "https://www.qjq.gov.cn/col/col1389659/art/2026/art_91a4137f877049f28b16a314d12943d3.html",
    rules: { subjects: ["英语", "历史", "数学", "心理健康"], stage: "中学", hukou: "none", needMaster: true, schoolGate: null, honorGate: null, certLevel: "none", audience: "fresh" } },

  { id: 73, city: "衢州市", district: "柯城区", batch: "校园招聘（浙师大专场）", early: true, stage: "中学",
    title: "柯城区教育局招聘2026年优秀应届毕业生公告（初中各学科）",
    posts: "初中语文2、数学3、英语2、科学2、社会3、心理健康1",
    count: "13名",
    staffing: "事业编", enroll: "浙师大专场现场报名（2026年3月，详见公告）", exam: "详见公告",
    condition: "2026届硕士及以上；户籍不限；38周岁以下（博士43）；品学兼优；定向/委培/在职人员不列入",
    url: "https://www.kecheng.gov.cn/col/col1229769719/art/2026/art_256c1c9bb56740e78d66d6d7b218285c.html",
    rules: { subjects: ["语文", "数学", "英语", "科学", "社会", "心理健康"], stage: "中学", hukou: "none", needMaster: true, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 74, city: "衢州市", district: "柯城区", batch: "校园招聘（浙师大专场）", early: true, stage: "小学、中学",
    title: "柯城区教育局招聘2026年优秀应届毕业生公告（中小学体育）",
    posts: "中小学体育教师",
    count: "2名",
    staffing: "事业编", enroll: "浙师大专场现场报名（2026年3月，详见公告）", exam: "详见公告",
    condition: "2026届本科及以上（体育学类专业）；户籍不限；38周岁以下（博士43）",
    url: "https://www.kecheng.gov.cn/col/col1229769719/art/2026/art_256c1c9bb56740e78d66d6d7b218285c.html",
    rules: { subjects: ["体育"], stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 75, city: "台州市", district: "黄岩区", batch: "社招统考", early: false, stage: "初中",
    title: "2026年台州市黄岩区教育局公开招聘教师公告",
    posts: "初中各学科（见岗位一览表）",
    count: "25名",
    staffing: "全额补助事业编", enroll: "详见公告", exam: "详见公告",
    condition: "户籍不限；面向2026年应届毕业生（在读非应届不能报考）；各岗位学历/专业/教资要求见岗位一览表；台州市内在编教师报考须单位同意",
    url: "http://qssy.zjks.com/tyzpwb/website/queryDetail.htm?mkxh=2&tzid=2717",
    rules: { stage: "初中", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 76, city: "宁波市", district: "北仑区", batch: "提前批/统考多批次", early: true, stage: "小学、中学",
    title: "2026年宁波市北仑区教育局公开招聘事业编制教师公告",
    posts: "北仑中学专场、仑教英才、仑教优才、优秀教育人才（含中小学各学科，见附件岗位表）",
    count: "195名",
    staffing: "事业编", enroll: "分批网报：北仑中学专场12月3日-12月10日；仑教英才12月8日-12月15日；仑教优才12月8日-2026年3月2日；优秀教育人才12月8日-2026年2月2日", exam: "北仑中学专场12月13日；仑教英才12月27日（多地设考点）；仑教优才2026年3月14日",
    condition: "各计划学历/户籍/荣誉条件不同，详见附件岗位表；全日制本科毕业于国内知名高校的紧缺人才最高30万安家补助；2026年9月30日前取得学历学位（博士12月31日）",
    url: "https://www.bl.gov.cn/art/2025/12/2/art_1229055347_4701681.html",
    rules: { stage: "小学、中学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: "unknown", certLevel: "unknown", audience: "fresh" } },

  { id: 77, city: "丽水市", district: "松阳县", batch: "社招统考", early: false, stage: "小学、中学",
    title: "2026年松阳县教育系统公开招聘中小学、幼儿园教师公告(一)（中小学岗）",
    posts: "高中美术、中学数学、中小学体育",
    count: "共10名（含学前教育岗）",
    staffing: "事业编", enroll: "详见公告（户籍以2026年5月12日为准）", exam: "详见公告",
    condition: "限2026届应届毕业生；高中美术/中学数学/中小学体育户籍不限；本科及以上+学位；18-38周岁；报名时须具备相应教师资格证（应届硕士可2027年8月31日前取得）；普通话二级乙等",
    url: "https://www.songyang.gov.cn/col/col1229355058/art/2026/art_31a02f9bcc604fd88bb5f83dd87fc514.html",
    rules: { subjects: ["美术", "数学", "体育"], stage: "小学、中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 78, city: "丽水市", district: "松阳县", batch: "社招统考", early: false, stage: "幼儿园",
    title: "2026年松阳县教育系统公开招聘中小学、幼儿园教师公告(一)（学前教育岗）",
    posts: "学前教育1、学前教育2岗位",
    count: "共10名（含中小学岗）",
    staffing: "事业编", enroll: "详见公告（户籍以2026年5月12日为准）", exam: "详见公告",
    condition: "限2026届应届毕业生；限松阳县户籍（或曾具松阳户籍/学籍、配偶松阳户籍）；学前教育1须本科+学位，学前教育2本科即可学位不限；须幼儿园教师资格证（专业不限）；18-38周岁",
    url: "https://www.songyang.gov.cn/col/col1229355058/art/2026/art_31a02f9bcc604fd88bb5f83dd87fc514.html",
    rules: { stage: "幼儿园", hukou: "松阳县", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 79, city: "台州市", district: "温岭市", batch: "提前批（浙师大专场）", early: true, stage: "中学",
    title: "2026年温岭市面向普通高校毕业生公开招聘教师公告",
    posts: "高中语文2/数学2/英语4/化学3/政治1/历史1、初中语文7及其他学科（见计划表）",
    count: "46名",
    staffing: "事业编", enroll: "2025年11月5日9:00-11月8日11:30（zouwl.cn）", exam: "笔试11月8日下午（浙师大）；面试11月22日",
    condition: "硕士及以上（往届须持证）；或2026届本科满足之一：部属高校毕业/国奖或省政府奖学金或省优毕/全国或省师范生技能竞赛三等奖及以上/省重点建设高校师范类且前6学期综测前70%/师范类且综测前20%；30周岁以下（硕士35）；服务期不少于6年",
    url: "https://www.wl.gov.cn/col/col1402173/index.html",
    rules: { stage: "中学", hukou: "none", needMaster: false, schoolGate: null, honorGate: "省师范生技能竞赛三等奖、综合考评前20%或省级以上荣誉（多通道详见公告）", certLevel: "none", audience: "fresh" } },

  { id: 80, city: "杭州市", district: "省级机关幼儿园", batch: "统招", early: false, stage: "幼儿园",
    title: "浙江省机关事务管理局直属幼儿园2026年公开招录（聘）幼儿教师公告",
    posts: "北山、武林门、保俶、府苑、滨江幼儿园（均在杭州市区）",
    count: "幼儿教师7名",
    staffing: "事业编（公益二类事业单位）", enroll: "详见公告（2025年11月13日发布）", exam: "详见公告",
    condition: "限浙江省户籍或生源的2026届毕业生（2024/2025届未入编者、视同应届者也可报）；学历/专业等要求见招考计划表",
    url: "https://rlsbt.zj.gov.cn/art/2025/11/13/art_1229743683_58943213.html",
    rules: { stage: "幼儿园", hukou: "zhejiang", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 81, city: "金华市", district: "开发区", batch: "校园招聘", early: true, stage: "小学、中学、幼儿园",
    title: "金华经济技术开发区公办学校（幼儿园）面向2026届毕业生公开招聘教师公告",
    posts: "开发区公办中小学、幼儿园（见岗位表）",
    count: "详见公告",
    staffing: "事业编", enroll: "现场报名：华师大11月3-4日 / 杭师大11月5-6日 / 浙师大11月3-8日", exam: "详见公告",
    condition: "面向2026届全国普通高校毕业生；具体学历/户籍/荣誉条件详见公告及岗位表",
    url: "http://kfq.jinhua.gov.cn/art/2025/10/27/art_1229098077_4306561.html",
    rules: { stage: "小学、中学、幼儿园", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: "unknown", certLevel: "unknown", audience: "fresh" } },

  // ============ 特殊教育专项（2026年，共10条；特教岗归入小学学段 tab） ============
  { id: 82, city: "温州市", district: "瑞安市", batch: "提前批", early: true, stage: "小学",
    title: "瑞安市特殊教育学校面向2026届毕业生提前批招聘特教教师公告",
    posts: "瑞安市特殊教育学校 特教教师",
    count: "1名",
    staffing: "事业编", enroll: "详见公告（提前批，2025年9-12月发布）", exam: "特殊教育专业知识笔试 + 试讲/模拟上课",
    condition: "2026届应届本科及以上并具学士学位；专业口径宽，接受特殊教育学、教育康复学、康复治疗学、心理学类等相关专业；须特殊教育学科教资（应届可凭国考合格证明）",
    url: "http://www.ruian.gov.cn/",
    rules: { subjects: ["特殊教育"], stage: "小学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 83, city: "温州市", district: "泰顺县", batch: "提前批", early: true, stage: "小学",
    title: "泰顺县2026年提前批公开招聘教师公告（含特教岗位）",
    posts: "泰顺县特殊教育岗位（含于15人计划中）",
    count: "特教岗位（含于15名总计划内）",
    staffing: "事业编", enroll: "详见公告（提前批）", exam: "特殊教育专业知识 + 面试",
    condition: "本科或硕士研究生；38周岁以下；专业及教资要求详见岗位表",
    url: "http://www.ts.gov.cn/",
    rules: { subjects: ["特殊教育"], stage: "小学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 84, city: "杭州市", district: "西湖区", batch: "提前批", early: true, stage: "小学",
    title: "杭州紫荆花学校（西湖区特殊教育学校）教师招聘公告",
    posts: "杭州紫荆花学校 特教教师",
    count: "若干名",
    staffing: "非编合同制（同工同酬，表现优秀优先入编）", enroll: "详见公告", exam: "特殊教育专业知识 + 试讲",
    condition: "须硕士研究生；特殊教育类、康复类专业；非编合同制，同工同酬且有优先入编通道",
    url: "https://www.hzxh.gov.cn/",
    rules: { subjects: ["特殊教育"], stage: "小学", hukou: "unknown", needMaster: true, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 85, city: "杭州市", district: "建德市", batch: "社招", early: false, stage: "小学",
    title: "建德市2026年公开招聘中小学幼儿园教师公告（含特教教师2名）",
    posts: "建德市特殊教育学校 特教教师",
    count: "2名",
    staffing: "事业编", enroll: "详见公告（社招，2026年3-7月）", exam: "特殊教育专业知识 + 面试",
    condition: "本科及以上；应届生须浙江户籍，社会人员须建德户籍；须特殊教育学科教资",
    url: "https://www.jiande.gov.cn/",
    rules: { subjects: ["特殊教育"], stage: "小学", hukou: "zhejiang", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 86, city: "杭州市", district: "富阳区", batch: "社招", early: false, stage: "小学",
    title: "杭州市富阳区特殊教育学校2026年招聘教师公告",
    posts: "富阳区特殊教育学校 特教教师",
    count: "1名",
    staffing: "事业编", enroll: "详见公告（社招）", exam: "特殊教育专业知识 + 试讲",
    condition: "本科及以上；须特殊教育专业；须特殊教育学科教资",
    url: "https://www.fuyang.gov.cn/",
    rules: { subjects: ["特殊教育"], stage: "小学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 87, city: "杭州市", district: "富阳区", batch: "社招", early: false, stage: "小学",
    title: "浙江省盲人学校2026年公开招聘教师公告",
    posts: "浙江省盲人学校（富阳）特教教师",
    count: "1名",
    staffing: "事业编", enroll: "详见公告（社招应届批次）", exam: "特殊教育专业知识 + 面试",
    condition: "须硕士研究生且为特殊教育学专业；须特殊教育学科教资",
    url: "https://www.fuyang.gov.cn/",
    rules: { subjects: ["特殊教育"], stage: "小学", hukou: "unknown", needMaster: true, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 88, city: "温州市", district: "市直属", batch: "社招", early: false, stage: "小学",
    title: "温州市特殊教育学校2026年公开招聘事业编教师公告",
    posts: "温州市特殊教育学校 教师（语文/学科教学方向）",
    count: "1名",
    staffing: "事业编", enroll: "2026年7月（社招）", exam: "笔试40%+面试60%；备课60分钟+模拟课堂12分钟+结构化面试，面试合格线75分",
    condition: "须硕士研究生；中国语言文学类、新闻传播学类、教育学类专业可报；须高中及以上学段相应学科教资；户籍不限",
    url: "https://rlsbt.zj.gov.cn/",
    rules: { subjects: ["特殊教育", "语文"], stage: "小学", hukou: "none", needMaster: true, schoolGate: null, honorGate: null, certLevel: "senior", audience: "fresh" } },

  { id: 89, city: "宁波市", district: "海曙区", batch: "社招", early: false, stage: "小学",
    title: "宁波市海曙区2026年第二批事业单位公开招聘工作人员公告（专曙优师·特教教师）",
    posts: "海曙区 特教教师（第二批共52人）",
    count: "1名",
    staffing: "事业编", enroll: "详见公告（社招第二批）", exam: "特殊教育专业知识 + 面试",
    condition: "本科及以上；具体要求详见公告岗位表",
    url: "https://www.haishu.gov.cn/",
    rules: { subjects: ["特殊教育"], stage: "小学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "any", audience: "fresh" } },

  { id: 90, city: "绍兴市", district: "越城区", batch: "社招", early: false, stage: "小学",
    title: "绍兴市越城区育才学校（培智/自闭症）2026年合同制教师招聘公告",
    posts: "越城区育才学校 合同制教师（培智/自闭症方向）",
    count: "4名",
    staffing: "劳务派遣（合同制）", enroll: "2026年7月（社招）", exam: "面试为主",
    condition: "门槛极低：有爱心、能接纳特殊儿童即可报考，无严格专业与教资限制；注意为劳务派遣非编岗位",
    url: "https://www.sxyc.gov.cn/",
    rules: { subjects: ["特殊教育"], stage: "小学", hukou: "unknown", needMaster: false, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },

  { id: 91, city: "杭州市", district: "浙江特殊教育职业学院", batch: "高校招聘", early: false, stage: "高校",
    title: "浙江特殊教育职业学院2026年专任教师招聘公告",
    posts: "高校专任教师（康复辅具、思政、体育等方向）",
    count: "若干名",
    staffing: "事业编（高校）", enroll: "2026年3月（高校招聘）", exam: "详见公告",
    condition: "高校教师岗，一般要求硕士及以上；康复辅具、思政、体育等专业；不适合本科应届生报考，仅作数据留存",
    url: "https://www.zcmu.edu.cn/",
    rules: { subjects: [], stage: "高校", hukou: "none", needMaster: true, schoolGate: null, honorGate: null, certLevel: "unknown", audience: "fresh" } },
];
